version: '3'
services:
  jekyll:
    image: ruby:3.2.2
    working_dir: /usr/src/app
    volumes:
      - "$PWD:/usr/src/app"
    ports:
      - "35729:35729"
      - "4000:4000"
    command: >
      bash -c "
      bundle config set --local path '/usr/src/app/vendor' &&
      bundle exec jekyll serve --trace --livereload --host=0.0.0.0"
